### ISSUE TITLE
Support socket files in mysql mode

### ISSUE THREAD

**Issue by andlabs** [knq/dburl#2]
I use [this](https://github.com/ezzatron/mysql-ad-hoc) to run local MySQL servers, and I'd like to be able to send the Unix sockets one would use with it (`db/mysql.sock`, for instance) into xo. It seems the code explicitly rejects `+unix` protocols; is there some other way I can specify a Unix socket? If not, could it be added? Thanks!

**Comment by kenshaw** [comment]
I believe you should just be able to pass the path: `mysql+unix:/path/to/socket`

**Comment by kenshaw** [comment]
I just checked, and the MySQL code for unix sockets had gotten messed up when I moved it to this package. I will fix this shortly. Apologies!

**Comment by andlabs** [comment]
Cool, thanks!

**Comment by kenshaw** [comment]
This should work correctly now. Please do a `go get -u` for xo, and xo should work like this:

`xo -o models mysql+unix:/path/to/mysql.sock/dbname`
